# Generated by Django 3.1.7 on 2021-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='where',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hints',
            name='where',
            field=models.CharField(default='', max_length=10),
        ),
    ]
