# Generated by Django 3.1.7 on 2021-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210422_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('fin_hint_id', models.IntegerField()),
                ('fin_time', models.CharField(max_length=100)),
                ('cur_score', models.IntegerField()),
                ('get_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='cd_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='hint',
            name='hint_choices',
            field=models.CharField(choices=[(1, 'standard'), (2, 'interactive'), (3, 'photo'), (4, 'quiz')], max_length=40),
        ),
    ]
