# Generated by Django 3.1.7 on 2021-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210424_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Others',
        ),
    ]
