# Generated by Django 3.1.7 on 2021-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_id', models.IntegerField()),
                ('hint_choices', models.CharField(choices=[('interactivate', 'Interactivate')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('basic_score', models.IntegerField()),
                ('bonus_score', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('done', models.CharField(max_length=10)),
            ],
        ),
    ]
