# Generated by Django 3.1.7 on 2021-04-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hints',
            old_name='groups',
            new_name='whichgroup',
        ),
    ]
